# ========================================
# 应用配置 | Application Configuration
# ========================================
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期 | Cookie expires in 30 days
    session:
      cookie:
        max-age: 2592000

spring:
  # 空间图片分表 | Space picture sharding configuration
  shardingsphere:
    datasource:
      names: intellipichub
      intellipichub:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/intellipichub
        username: root
        # 必填
        password: your_mysql_password
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: intellipichub.picture  # 动态分表 | Dynamic table sharding
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法 | Use custom sharding algorithm
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.jiahe.intellipichub.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
  application:
    name: jiahe-IntelliPicHub
  # 数据库配置 | Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intellipichub
    username: root
    # 必填
    password: your_mysql_password
  # Redis 配置 | Redis configuration
  session:
    store-type: redis
    # session 30 天过期 | Session expires in 30 days
    timeout: 2592000
  redis:
    database: 0
    host: 127.0.0.1
    # 必填
    password: your_redis_password
    port: 6379
    timeout: 5000
  # session配置 | Session configuration
  # 文件上传大小 | File upload size limit
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志 | Enable logging only in development environment
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名 | Global logical delete entity field name
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）| Logical deleted value (default is 1)
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）| Logical not deleted value (default is 0)
    enable-sql-runner: true

# 接口文档配置 | API documentation configuration
knife4j:
  enable: true
  # 开启认证 | Enable authentication
  basic:
    # 必填
    enable: true
    username: admin
    # 必填
    password: your_password
  openapi:
    title: interface doc
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jiahe.intellipichub.controller

# 腾讯云 COS 配置 | Tencent Cloud COS configuration
# 必填
cos:
  client:
    host: your_cos_host
    secretID: your_cos_secret_id
    secretKey: your_cos_secret_key
    region: your_cos_region
    bucket: your_cos_bucket_name

# 阿里云 AI 配置 | Alibaba Cloud AI configuration
# 如果要ai扩图功能的话则必填
aliYunAi:
  apiKey: your_aliyun_ai_api_key

